version: '3.8'

services:
  mysql:
    build: .
    container_name: salil
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: salil
      MYSQL_DATABASE: salil
    volumes:
      - ./backup.sql:/var/opt/backup.sql
      - ./restore_db.sh:/usr/local/bin/restore_db.sh
    entrypoint: ["sh", "-c", "/usr/local/bin/restore_db.sh && docker-entrypoint.sh mysqld"]
